# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get diff pattern 1
        id: check_diff
        if: ${{ github.event_name == 'pull_request' }}
        uses: ./.github/workflows/diff_check
        with:
          target_list: ".github/"
      - name: print result
        run: |
          echo result ${{ steps.check_diff.outputs.is_contain }} 

      - name: get diff pattern 2
        id: get_diff_2
        if: ${{ github.event_name == 'pull_request' }}
        uses: ./.github/workflows/diff_check_2
      - name: print result 2
        run: |
          echo result ${{ steps.get_diff_2.outputs.diff }}
      - name: build source
        if: contains(steps.get_diff_2.outputs.diff, 'src/')
        run: |
          echo build source

      - name: get diff pattern 3 
        run: |
          BASE_REF=$GITHUB_BASE_REF HEAD_REF=$GITHUB_HEAD_REF .github/workflows/diff_build.sh